### ISSUE TITLE
Warning during install, error during test. 

### ISSUE THREAD

**Issue by naeemiqbal** [ahmednuaman/javascript-tests#1]
Warning during install. 
npm WARN optional dep failed, continuing fsevents@0.3.1

Error during test,
C:\zRnd\others\nodetest>npm test

> javascript-tests@0.0.1 test C:\zRnd\others\nodetest
> karma start karma.conf.js

'karma' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

C:\zRnd\others\nodetest>install karma
'install' is not recognized as an internal or external command,
operable program or batch file.

C:\zRnd\others\nodetest>install -g karma
'install' is not recognized as an internal or external command,
operable program or batch file.

C:\zRnd\others\nodetest>npm install -g karma
## npm WARN optional dep failed, continuing fsevents@0.3.1

> ws@0.4.32 install C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma\node_
> modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\no
de_modules\socket.io-client\node_modules\ws>node "C:\Program Files (x86)\nodejs\
node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js"
rebuild
karma@0.12.28 C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── mime@1.2.11
├── colors@0.6.2
├── rimraf@2.2.8
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.40 (amdefine@0.1.0)
├── lodash@2.4.1
├── chokidar@0.12.1 (async-each@0.1.6, readdirp@1.2.0)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── log4js@0.6.21 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0
.5, response-time@2.0.1, bytes@1.0.0, vhost@3.0.0, basic-auth-connect@1.0.0, med
ia-typer@0.3.0, on-headers@1.0.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@0.4.
5, qs@2.2.4, finalhandler@0.2.0, connect-timeout@1.3.0, method-override@2.2.0, d
ebug@2.0.0, serve-favicon@2.1.7, morgan@1.3.2, type-is@1.5.4, multiparty@3.3.2,
express-session@1.8.2, serve-static@1.6.4, csurf@1.6.3, body-parser@1.8.4, error
handler@1.2.3, serve-index@1.2.1, compression@1.1.2)
└── socket.io@0.9.17 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-c
lient@0.9.16)

C:\zRnd\others\nodetest>npm test

> javascript-tests@0.0.1 test C:\zRnd\others\nodetest
> karma start karma.conf.js

'karma' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

C:\zRnd\others\nodetest>install karma -g
'install' is not recognized as an internal or external command,
operable program or batch file.

C:\zRnd\others\nodetest>npm install karma -g
npm WARN optional dep failed, continuing fsevents@0.3.1
\

> ws@0.4.32 install C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma\node_
> modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\no
de_modules\socket.io-client\node_modules\ws>node "C:\Program Files (x86)\nodejs\
node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js"
rebuild
karma@0.12.28 C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── colors@0.6.2
├── rimraf@2.2.8
├── mime@1.2.11
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── source-map@0.1.40 (amdefine@0.1.0)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── chokidar@0.12.1 (async-each@0.1.6, readdirp@1.2.0)
├── log4js@0.6.21 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── lodash@2.4.1
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── connect@2.26.6 (fresh@0.2.4, cookie@0.1.2, cookie-signature@1.0.5, pause@0.0
.1, response-time@2.0.1, bytes@1.0.0, basic-auth-connect@1.0.0, vhost@3.0.0, med
ia-typer@0.3.0, on-headers@1.0.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@0.4.
5, connect-timeout@1.3.0, qs@2.2.4, finalhandler@0.2.0, method-override@2.2.0, d
ebug@2.0.0, morgan@1.3.2, serve-favicon@2.1.7, serve-static@1.6.4, express-sessi
on@1.8.2, compression@1.1.2, body-parser@1.8.4, multiparty@3.3.2, csurf@1.6.3, e
rrorhandler@1.2.3, type-is@1.5.4, serve-index@1.2.1)
└── socket.io@0.9.17 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-c
lient@0.9.16)

C:\zRnd\others\nodetest>npm install karma-cli -g
C:\Users\niqbal\AppData\Roaming\npm\karma -> C:\Users\niqbal\AppData\Roaming\npm
\node_modules\karma-cli\bin\karma
karma-cli@0.0.4 C:\Users\niqbal\AppData\Roaming\npm\node_modules\karma-cli
└── resolve@0.5.1

C:\zRnd\others\nodetest>npm test

> javascript-tests@0.0.1 test C:\zRnd\others\nodetest
> karma start karma.conf.js

INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 7)]: Connected on socket _-4j-_OMWGi-C_KtzDf8 wit
h id 40833389
PhantomJS 1.9.8 (Windows 7) clone object should clone an object FAILED
        Expected {  } to equal { name : 'Ahmed', age : 27, skills : [ 'cycling',
 'walking', 'eating' ] }.
PhantomJS 1.9.8 (Windows 7) flatten array should flatten an array FAILED
        Expected [ 1, 2, [ 1, 2, [ 3, 4, 5, [ 1 ] ] ], 2, [ 2 ] ] to equal [ 1,
1, 1, 2, 2, 2, 2, 3, 4, 5 ].
PhantomJS 1.9.8 (Windows 7) scoping should correctly deal with scoping `this` ba
ck to the callee FAILED
        Expected undefined to be 'bar'.
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.008 secs / 0.00
4 secs)
INFO [IE 9.0.0 (Windows 7)]: Connected on socket wDno1ErNDtoXUy_FzDf9 with id ma
nual-7821
PhantomJS 1.9.8 (Windows 7) clone object should clone an object FAILED
        Expected {  } to equal { name : 'Ahmed', age : 27, skills : [ 'cycling',
 'walking', 'eating' ] }.
PhantomJS 1.9.8 (Windows 7) flatten array should flatten an array FAILED
        Expected [ 1, 2, [ 1, 2, [ 3, 4, 5, [ 1 ] ] ], 2, [ 2 ] ] to equal [ 1,
1, 1, 2, 2, 2, 2, 3, 4, 5 ].
PhantomJS 1.9.8 (Windows 7) scoping should correctly deal with scoping `this` ba
ck to the callee FAILED
        Expected undefined to be 'bar'.
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
IE 9.0.0 (Windows 7) clone object should clone an object FAILED
        Expected {  } to equal { name : 'Ahmed', age : 27, skills : [ 'cycling',
 'walking', 'eating' ] }.
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
IE 9.0.0 (Windows 7) flatten array should flatten an array FAILED
        Expected [ 1, 2, [ 1, 2, [ 3, 4, 5, [ 1 ] ] ], 2, [ 2 ] ] to equal [ 1,
1, 1, 2, 2, 2, 2, 3, 4, 5 ].
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
IE 9.0.0 (Windows 7) scoping should correctly deal with scoping `this` back to t
he callee FAILED
        Expected undefined to be 'bar'.
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.011 secs / 0.00
5 secs)
IE 9.0.0 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.015 secs / 0.004 secs)

WARN [web-server]: 404: /favicon.ico

**Comment by CarlBateman** [comment]
I found the readme to be misleading (and terse). You might like to include the above comment to clarify.
